# Generated by Django 5.0.3 on 2024-06-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '001__intial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Doctor care', 'Doctor care'), ('Nursing care', 'Nursing care'), ('Medical social services', 'Medical social services'), ('Homemaker or basic assistance care', 'Homemaker or basic assistance care')], default='Doctor care', max_length=50),
        ),
    ]
